@startuml
class Persona {
-nombre : String
-apellidos : String
-DNI : String
-fechaCaducidadCarnet : Date
-anioNacimiento : int

+Persona(String nombre, String apellidos, String DNI, Date fechaCaducidadCarnet, int anioNacimiento)
+String getNombre()
+void setNombre(String nombre)
+String getApellidos()
+void setApellidos(String apellidos)
+String getDNI()
+void setDNI(String DNI)
+Date getFechaCaducidadCarnet()
+void setFechaCaducidadCarnet(Date fechaCaducidadCarnet)
+int getAnioNacimiento()
+void setAnioNacimiento(int anioNacimiento)
+int calcularExperiencia()
}
@enduml